### ISSUE TITLE
Support for Linux Mint 19.3 and Filecloud 19.3

### ISSUE THREAD

**Issue by martinseener** [derek-shnosh/filecloudsync-install#1]
Hi,
thanks alot for your effort. I used the most recent Filecloud install script first (haven't found this script before) and installed it using their script. It installed a ton of additional packages, broke my OpenSSL (version mismatch) and then also didn't work due to missing system tray support.
I run the above system and want to use the latest version of FC.
Do you know what i have to change in your script, so that it works correctly?
Thanks for the great work!

**Comment by derek-shnosh** [comment]
@martinseener - wow, sorry for the extremely late response here... I didn't get a notification for this and just noticed this issue.

I believe Linux Mint is Ubuntu/Debian based, so this script should work fine.
